=Portalverbund Testföderation
== Einbinden eines Service Providers

zur Testfederation erfolgt mittels folgender Schritte:

. Export der Metadaten des SP. Dabei ist zu prüfen, dass die Metadaten den Anforderungen genügen.
  Die automatisch generierten Metadaten sind fast immer unzureichend. Beispiele für korrekte
  Metadaten sind die Entites für idp5.test.portalverbund.gv.at (IDP) und
  echo.test.portalverbund.gv.at (SP).
. Validierung der Metadaten gegen XSD und Schematron-Regeln.
. Korrigieren der Metadaten und Wiederholung der Schritte 1 und 2 bis alle Mängel behoben sind.
. Hochladen in die Metadatenregistry. Derzeit per Mail an webmaster@test.portalverbund.gv.at
. Überprüfen ob die Metadaten korrekt im Metadatenfeed erscheinen.
. Konfigurieren des SP, dass die Metadaten regelmäßig vom MD-Feed der Testfederation bezogen werden
  (http://md.test.portalverbund.gv.at/metadata.xml). Wird das vom Produkt nicht unterstützt,
  so ist mittles Scripts zu realisieren, dass Download, Signaturprüfung und Import automatisch
 erfolgen. Für ADFS können die Metadaten auf Anfrage in einem speziellen Format bereitgestellt werden.
. Eintragen des IdP-Discovery Service in der lokalen SP-Konfiguration. Die Adresse ist
  https://disco.test.portalverbund.gv.at/role/idp.ds. Achtung! Das Protokoll ist das SAMLDS
  protokoll, nicht das auf Common Cookies basierende IDP Discovery Profile. Der Aufruf erfolgt über
  einen URL mit folgenden Komponenten:
** Hostname + Pfad: https://disco.test.portalverbund.gv.at/role/idp.ds
** entityID-Parameter: enthält URL-codierte entityID
** Return-Pfad: enthält URL-codierte Rückgabeadresse
  Beispiel: /role/idp.ds?entityID=https%3A%2F%2Fecho.test.portalverbund.gv.at%2Fsp.xml&return=https%3A%2F%2Fecho.test.portalverbund.gv.at%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253A52889d0c6e0396b95f185a65ea888327cabbc23be0657f92544ee43a98d9ca37
. Zum Abschluss sind die Metadaten der eigenen Entity herunterzuladen und unter dem EntityDescriptor (als URL) veröffentlichen.
. Einfacher Test eines SP-initiated Logins mit idp5.test.portalverbund.gv.at. Anmeldung mit
  tester@testinetics.at /test.


link:index.html[Home]