---
position: 5
---
:showtitle:
:page-shortname: HowTo-SP
:page-title: HowTo SP
:page-position: 3
:page-description: Verwaltungsportalverbund Testumgebung

== Einbinden eines Service Providers

in die Testfederation erfolgt mittels folgender Schritte:

* Export der Metadaten des SP. Dabei ist zu prüfen, dass die Metadaten den Anforderungen genügen.
  Die automatisch generierten Metadaten sind fast immer unzureichend. Beispiele für korrekte
  Metadaten sind die Entities für \https://mdfeed.test.portalverbund.gv.at/unsigned/idp5TestPortalverbundGvAt_idpXml.xml[idp5.test.portalverbund.gv.at] (IDP) und
  \https://mdfeed.test.portalverbund.gv.at/unsigned/sp1TestWpvPortalverbundAt_spXml/ed.xml[sp1.test.portalverbund.gv.at] (SP).
  Typische Mängel sind:
  ** entityID ist kein URI (beginnt nicht mit http://, https:// oder urn://)
  ** Fehlende EntityCategory: Welche Attribute zwischen IDP und SP ausgetauscht werden wird über die
     EntityCategory angegeben, das ist derzeit \http://www.ref.gv.at/ns/names/agiz/pvp/egovtoken und
     \http://www.ref.gv.at/ns/names/agiz/pvp/no-attributes. Andere Attributangaben in den Metadaten
     sind nicht maßgeblich und sollten daher entfernt werden.
  ** In den mdui: Elementen sind sinnvolle Angaben zu ergänzen, um automatisches IDP- und Service
     Discovery zu steuern.
  ** In den alg: Elementen sind die tatsächlich erlaubten Krypto-Algorithmen anzugeben (abhängig
     von der Konfiguration)
* Validierung der Metadaten mit dem PVP2 Profil: http://mdval.test.portalverbund.at/
* Korrigieren der Metadaten und Wiederholung der Schritte 1 und 2 bis alle Mängel behoben sind.
* Hochladen in die Metadatenregistry. (Siehe
  link:metadataupload.html[Metadaten melden oder aktualisieren])
* Überprüfen ob die Metadaten korrekt im Metadatenfeed erscheinen.
* Konfigurieren des SP, dass die Metadaten regelmäßig vom MD-Feed der Testfederation bezogen werden
  (http://mdfeed.test.portalverbund.gv.at/metadata.xml). Wird das vom Produkt nicht unterstützt,
  so ist mittles Scripts zu realisieren, dass Download, Signaturprüfung und Import automatisch
  erfolgen.
* Eintragen des IdP-Discovery Service in der lokalen SP-Konfiguration. Die Adresse ist
  https://disco.test.portalverbund.gv.at/role/idp.ds. Achtung! Das Protokoll ist das SAMLDS
  Protokoll, nicht das auf Common Cookies basierende IDP Discovery Profile. Der Aufruf erfolgt über
  einen URL mit folgenden Komponenten:
** Hostname + Pfad: https://disco.test.portalverbund.gv.at/role/idp.ds
** entityID-Parameter: enthält URL-codierte entityID
** Return-Pfad: enthält URL-codierte Rückgabeadresse
  +++<span class="word-wrap">Beispiel: /role/idp.ds?entityID=https%3A%2F%2Fecho.test.portalverbund.gv.at%2Fsp.xml&return=https%3A%2F%2Fecho.test.portalverbund.gv.at%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253A52889d0c6e0396b95f185a65ea888327cabbc23be0657f92544ee43a98d9ca37 </span>+++
* Einfacher Test eines SP-initiated Logins mit idp5.test.portalverbund.gv.at. Anmeldung mit
  User test@bmspot.gv.at PW test.

