= Verwaltungportalverbund Testföderation (Home)

.Zweck
Zweck der Testfedertion ist die Interoperabilität und Konformität von SPs und IdPs
zu prüfen. Damit soll erreicht werden, dass Produkte auf ihre Konformität mit PVP2 getestet werden
können, Konfigurationsprobleme erkannt werden bevor eine Instanz in den Produktionsbetrieb
eingegliedert wird und Sicherheitsprobleme frühzeitig erkannt werden.


.Testmöglichkeiten

* Erstellen und validieren von Metadaten
* Einbindung eines IDP oder SP in die Testfederation (= Aufnahme des EntityDescriptors in die Metadaten)
* IDPs
  ** Aufnahme in das IDP Discovery Service (implizit über die Metadaten)
  ** Einfacher Funktionstest mit dem Echoservice
* SPs
  ** Verwendung des zentralen IDP Discovery Service
  ** Einfacher Funktionstest mit den Test-IDP

.How-To
link:how-to-SP.html[SP zur Testföderation hinzufügen]


.Dienste

|====================
|Metadatenverwaltung | Anfrage an Webmaster at portalverbund.gv.at
|Metadatenvalidierung | http://mdval.test.portalverbund.at/
|Metadatenpublikation |http://mdfeed.test.portalverbund.gv.at/
|Echo-Service mit fix eingestelltem IdP | https://echo.test.portalverbund.gv.at/
|Echo-Service mit zentralem Discovery Service | https://sp3.test.portalverbund.gv.at/
|Echo-Service mit embedded Discovery Service | https://sp5.test.portalverbund.gv.at/
|Test IdP | https://idp5.test.portalverbund.gv.at/idp/profile/Status
|====================

.Metadaten-Feed

Die Metadaten sind regelmäßig (im Produktionsbetrieb z.B. stündlich doer täglich) vom 
Feed zu laden. Dann ist die Signatur zu prüfen und der IDP oder SP bei Änderungen zu 
aktualisieren. Die Metadaten sind mit folgendem Zertifikat signiert:
metadata_crt.pem
link:files/metadata_crt.pem[MD Signaturzertifikat]


.Referenzen
Die technischen Protokolle des Portalverbunds sind u.a. in folgeneden Dokumenten definiert

++++
<ul>
<li>
<p>
<a href="http://reference.e-government.gv.at/fileadmin/user_upload/PVP2-S-Profil_2-1-2_20150601.pdf">PVP V2 S-Profil V2.1.2</a>
</p>
</li>
<li>
<p>
<a href="http://reference.e-government.gv.at/fileadmin/user_upload/PVP2-S-MD_2-1-2_20150601.pdf">PVP2 SAML Metadaten Management Spezifikation V2.1.2</a>
</p>
</li>
</ul>
++++
